export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST"
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS"
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL"
export const CLEAR_ERRORS = "CLEAR_ERRORS"